# Generated by Django 2.1.5 on 2019-02-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('podcast', models.FileField(upload_to='podcasts/')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
